AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-0b72821e2f351e396'  # Replace with a valid AMI ID
        #      KeyName: 'your-key-pair'           # Replace with your key pair name

